name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: ruff lint
        uses: astral-sh/ruff-action@v1

      - name: ruff format check
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
